/* This file is generated by Ziggy. */
declare module "ziggy-js" {
    interface RouteList {
        login: [];
        logout: [];
        "password.request": [];
        "password.reset": [
            {
                name: "token";
            }
        ];
        "password.email": [];
        "password.update": [];
        register: [];
        "user-profile-information.update": [];
        "user-password.update": [];
        "password.confirmation": [];
        "password.confirm": [];
        "two-factor.login": [];
        "two-factor.enable": [];
        "two-factor.confirm": [];
        "two-factor.disable": [];
        "two-factor.qr-code": [];
        "two-factor.secret-key": [];
        "two-factor.recovery-codes": [];
        "profile.show": [];
        "sanctum.csrf-cookie": [];
        "livewire.update": [];
        "livewire.upload-file": [];
        "livewire.preview-file": [
            {
                name: "filename";
            }
        ];
        "ignition.healthCheck": [];
        "ignition.executeSolution": [];
        "ignition.updateConfig": [];
        "dashboard.index": [];
        "dashboard.create": [];
        "dashboard.store": [];
        "dashboard.show": [
            {
                name: "dashboard";
            }
        ];
        "dashboard.edit": [
            {
                name: "dashboard";
            }
        ];
        "dashboard.update": [
            {
                name: "dashboard";
            }
        ];
        "dashboard.destroy": [
            {
                name: "dashboard";
            }
        ];
        "main-location.index": [];
        "main-location.create": [];
        "main-location.store": [];
        "main-location.show": [
            {
                name: "main_location";
            }
        ];
        "main-location.edit": [
            {
                name: "main_location";
            }
        ];
        "main-location.update": [
            {
                name: "main_location";
            }
        ];
        "main-location.destroy": [
            {
                name: "main_location";
            }
        ];
        "sub-location.index": [];
        "sub-location.create": [];
        "sub-location.store": [];
        "sub-location.show": [
            {
                name: "sub_location";
            }
        ];
        "sub-location.edit": [
            {
                name: "sub_location";
            }
        ];
        "sub-location.update": [
            {
                name: "sub_location";
            }
        ];
        "sub-location.destroy": [
            {
                name: "sub_location";
            }
        ];
        "detail-location.index": [];
        "detail-location.create": [];
        "detail-location.store": [];
        "detail-location.show": [
            {
                name: "detail_location";
            }
        ];
        "detail-location.edit": [
            {
                name: "detail_location";
            }
        ];
        "detail-location.update": [
            {
                name: "detail_location";
            }
        ];
        "detail-location.destroy": [
            {
                name: "detail_location";
            }
        ];
        getSubLocations: [];
    }
}
export {};
