/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token"
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm": [],
    "two-factor.login": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "profile.show": [],
    "sanctum.csrf-cookie": [],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename"
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "backsite.dashboard.index": [],
    "backsite.dashboard.create": [],
    "backsite.dashboard.store": [],
    "backsite.dashboard.show": [
        {
            "name": "dashboard"
        }
    ],
    "backsite.dashboard.edit": [
        {
            "name": "dashboard"
        }
    ],
    "backsite.dashboard.update": [
        {
            "name": "dashboard"
        }
    ],
    "backsite.dashboard.destroy": [
        {
            "name": "dashboard"
        }
    ],
    "backsite.main-location.index": [],
    "backsite.main-location.create": [],
    "backsite.main-location.store": [],
    "backsite.main-location.show": [
        {
            "name": "main_location"
        }
    ],
    "backsite.main-location.edit": [
        {
            "name": "main_location"
        }
    ],
    "backsite.main-location.update": [
        {
            "name": "main_location"
        }
    ],
    "backsite.main-location.destroy": [
        {
            "name": "main_location"
        }
    ],
    "backsite.sub-location.index": [],
    "backsite.sub-location.create": [],
    "backsite.sub-location.store": [],
    "backsite.sub-location.show": [
        {
            "name": "sub_location"
        }
    ],
    "backsite.sub-location.edit": [
        {
            "name": "sub_location"
        }
    ],
    "backsite.sub-location.update": [
        {
            "name": "sub_location"
        }
    ],
    "backsite.sub-location.destroy": [
        {
            "name": "sub_location"
        }
    ],
    "backsite.detail-location.index": [],
    "backsite.detail-location.create": [],
    "backsite.detail-location.store": [],
    "backsite.detail-location.show": [
        {
            "name": "detail_location"
        }
    ],
    "backsite.detail-location.edit": [
        {
            "name": "detail_location"
        }
    ],
    "backsite.detail-location.update": [
        {
            "name": "detail_location"
        }
    ],
    "backsite.detail-location.destroy": [
        {
            "name": "detail_location"
        }
    ],
    "backsite.getSubLocations": []
}
}
export {};
